/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as MortgageCalculatorImport } from "./routes/mortgage-calculator";

// Create Virtual Routes

const RecipeLazyImport = createFileRoute("/recipe")();
const AboutLazyImport = createFileRoute("/about")();
const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const RecipeLazyRoute = RecipeLazyImport.update({
  id: "/recipe",
  path: "/recipe",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/recipe.lazy").then((d) => d.Route));

const AboutLazyRoute = AboutLazyImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/about.lazy").then((d) => d.Route));

const MortgageCalculatorRoute = MortgageCalculatorImport.update({
  id: "/mortgage-calculator",
  path: "/mortgage-calculator",
  getParentRoute: () => rootRoute,
} as any);

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/mortgage-calculator": {
      id: "/mortgage-calculator";
      path: "/mortgage-calculator";
      fullPath: "/mortgage-calculator";
      preLoaderRoute: typeof MortgageCalculatorImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/recipe": {
      id: "/recipe";
      path: "/recipe";
      fullPath: "/recipe";
      preLoaderRoute: typeof RecipeLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/mortgage-calculator": typeof MortgageCalculatorRoute;
  "/about": typeof AboutLazyRoute;
  "/recipe": typeof RecipeLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/mortgage-calculator": typeof MortgageCalculatorRoute;
  "/about": typeof AboutLazyRoute;
  "/recipe": typeof RecipeLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexLazyRoute;
  "/mortgage-calculator": typeof MortgageCalculatorRoute;
  "/about": typeof AboutLazyRoute;
  "/recipe": typeof RecipeLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/mortgage-calculator" | "/about" | "/recipe";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/mortgage-calculator" | "/about" | "/recipe";
  id: "__root__" | "/" | "/mortgage-calculator" | "/about" | "/recipe";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  MortgageCalculatorRoute: typeof MortgageCalculatorRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  RecipeLazyRoute: typeof RecipeLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MortgageCalculatorRoute: MortgageCalculatorRoute,
  AboutLazyRoute: AboutLazyRoute,
  RecipeLazyRoute: RecipeLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mortgage-calculator",
        "/about",
        "/recipe"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/mortgage-calculator": {
      "filePath": "mortgage-calculator.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/recipe": {
      "filePath": "recipe.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
