/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MortgageCalculatorImport } from './routes/mortgage-calculator'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MortgageCalculatorRoute = MortgageCalculatorImport.update({
  id: '/mortgage-calculator',
  path: '/mortgage-calculator',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/mortgage-calculator': {
      id: '/mortgage-calculator'
      path: '/mortgage-calculator'
      fullPath: '/mortgage-calculator'
      preLoaderRoute: typeof MortgageCalculatorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mortgage-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mortgage-calculator'
  id: '__root__' | '/' | '/mortgage-calculator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MortgageCalculatorRoute: typeof MortgageCalculatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MortgageCalculatorRoute: MortgageCalculatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mortgage-calculator"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/mortgage-calculator": {
      "filePath": "mortgage-calculator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
